[settings]

  [settings.gaps]
  _top = 110.0
  _bottom = 110.0
  _left = 220.0
  _right = 220.0
  _windows_x = 20.0
  _windows_y = 20.0

  [settings.columns]
  _max_size_main = 10.0
  _max_size = 10.0
  _max_count = 10.0

  [[settings.window]]
  _class = "mpv"
  _floating = true

  [[settings.window]]
  _class = "chromium"
  _priority = "high"
  _floating = true

  [[settings.window]]
  _class = "pcmanfm"
  _floating = true

  [[settings.window]]
  _class = "gnome-control-center"
  _floating = true

  [[settings.column_config]]
  _windows = 1.0
  _workspace = "all"
  _column_sizes = 1.0

  [[settings.column_config]]
  _windows = 2.0
  _workspace = "all"
  _column_sizes = "1, 1"

  [[settings.column_config]]
  _windows = 3.0
  _workspace = "all"
  _column_sizes = "1, 2"

  [[settings.column_config]]
  _windows = 4.0
  _workspace = "all"
  _column_sizes = "1, 3"

  [[settings.column_config]]
  _windows = 5.0
  _workspace = "all"
  _column_sizes = "2, 3"

  [[settings.column_config]]
  _windows = 6.0
  _workspace = "all"
  _column_sizes = "2, 4"

  [[settings.column_config]]
  _windows = 7.0
  _workspace = "all"
  _column_sizes = "3, 4"
